org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false


## Environment Properties

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]

neo_version = 21.1.152
neo_version_range=[21.1.152,)
loader_version_range=[4,)

#read more on this at https://github.com/neoforged/NeoGradle/blob/NG_7.0/README.md#apply-parchment-mappings
# you can also find the latest versions at: https://parchmentmc.org/docs/getting-started
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

## Mod Properties

mod_id=toolboxutils
mod_name=Create: Toolbox Utils
mod_license=MIT
mod_version=0.1.0
mod_group_id=xyz.peatral.toolboxutils
mod_authors=Peatral
mod_credits=NoPlatypus for the idea
mod_description=A small addon to Create to make Toolboxes enchantable


## Dependencies

create_version = 6.0.4-59
ponder_version = 1.0.46
flywheel_version = 1.0.2
registrate_version = MC1.21-1.3.0+62

cloth_config_version = 11.1.118
jei_version = 19.10.0.126
